#!/bin/sh
# The script runs in the repo's root directory
# commitlint will inspect .git/COMMIT_EDITMSG
# because we are mounting the repo's .git dir
# into the container
#
# You can include a custom commitlint.config.js
# by mounting a local commitlint.config.js into
# the container, like so
#
# docker run --mount type=bind,source=${PWD}/.git,target=/app/.git \
#    type=bind,source=${PWD}/commitlint.config.js,target=/app/commitlint.config.js \
#    jamars-commitlint:0.1.0 sh -c 'commitlint -e'

RED='\033[0;31m'
GREEN='\033[1;32m'
YELLOW='\033[0;33m'
NOCOLOR='\033[0m'

result=0
# See if docker exists...
docker version > /dev/null 2>&1
if [ $? == 0 ]; then
  docker run --mount type=bind,source=${PWD}/.git,target=/app/.git\
    jamars-commitlint:0.1.0 sh -c 'commitlint -e'
  result=$?
  if [ $result != 0 ]; then
    echo -e "${RED}Invalid commit message!${NOCOLOR}"
    exit $result
  fi
else
  echo -e "${YELLOW}Please install docker to enable commitlint-in-docker${NOCOLOR}"
fi
